/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=release/origin-probe/wrangler.jsonc --env-file=release/origin-probe/.dev.vars.example --include-runtime=false --strict-vars=false --env-interface=OriginProbeEnv release/origin-probe/worker-configuration.d.ts` (hash: 35a2d4a323ef9a05b7ec202edc903f21)
interface __BaseEnv_OriginProbeEnv {
	R2_PUBLIC_BASE: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_OriginProbeEnv {}
}
interface OriginProbeEnv extends __BaseEnv_OriginProbeEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_PUBLIC_BASE">> {}
}
